services:
  app:
    build: .
    environment:
      HISTFILE: /app/.docker_history
    volumes:
      - .:/app
      - mix:/root/.mix
      - deps:/app/deps
      - node_modules:/app/assets/node_modules
      - build:/app/_build
      - assets:/app/priv/assets
    ports:
      - "4000:4000"

volumes:
  mix:
  deps:
  node_modules:
  build:
  assets:
