services:
  app:
    build: .
    environment:
      HISTFILE: /app/.docker_history
    volumes:
      - .:/app
      - mix:/root/.mix
      - deps:/app/deps
      - build:/app/_build
      - assets:/app/priv/assets
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  mix:
  deps:
  build:
  assets:
  postgres:
